refactoring the test workflow

diff --git a/release-version-check/action.yml b/release-version-check/action.yml
--- a/release-version-check/action.yml
+++ b/release-version-check/action.yml
@@ -1,4 +1,9 @@
 name: "Release Version Check"
+description: "Checks to make sure the version has been bumped before creating a release"
+author: "Bitwarden"
+branding:
+  icon: download
+  color: blue
 inputs:
   release-type:
     description: "Release options"
@@ -22,61 +27,69 @@ inputs:
     required: false
     default: ""
 outputs:
-  description: "The new version being released"
-  version: ${{ steps.new-version.outputs.version }}
+  version:
+    description: "The new version being released"
+    value: ${{ steps.new-version.outputs.version }}
+  status:
+    description: "The status of the job as a whole: ('success', 'fail')"
+    value: ${{ steps.status.outputs.status}}
 runs:
   using: "composite"
   steps:
     - name: Input validation
+      id: validation
+      shell: bash
       run: |
         release_valid_inputs=("Initial Release" "Redeploy" "Dry Run")
         if [[ ! "${release_valid_inputs[@]}" =~ "${{ inputs.release-type }}" ]]; then
           echo "[!] 'release-type' option only supports the following values: (${release_valid_inputs})"
-          exit 1
+          echo "::set-output name=step-failed::true"
         fi
 
         project_type_valid_inputs=("ts" "csharp")
         if [[ ! "${project_type_valid_inputs[@]}" =~ "${{ inputs.project-type }}" ]]; then
           echo "[!] 'project-type' option only supports the following values: (${project_type_valid_inputs})"
-          exit 1
+          echo "::set-output name=step-failed::true"
         fi
 
         if [ ! -f "${{ inputs.file }}" ]; then
           echo "[!] The relative path '${{ inputs.file}}' doesn't exist"
-          exit 1
+          echo "::set-output name=step-failed::true"
         fi
 
         monorepo_valid_inputs=("true" "false")
         if [[ ! "${monorepo_valid_inputs[@]}" =~ "${{ inputs.monorepo }}" ]]; then
           echo "[!] 'monorepo' option only supports the following values: (${monorepo_valid_inputs})"
-          exit 1
+          echo "::set-output name=step-failed::true"
         fi
 
         if [ "${{ inputs.monorepo }}" == "true" ] && [ "${{ inputs.monorepo-project }}" == "" ]; then
           echo "[!] using the 'monorepo' option requires the use of 'monorepo-project'"
-          exit 1
+          echo "::set-output name=step-failed::true"
         fi
 
 
     - name: Get project new version
+      shell: bash
       id: new-version
       run: |
         # Get version from file depending on project type
-        case "${{ inputs.type }}" in
+        case "${{ inputs.project-type }}" in
           "ts")
-            version=$( jq -r ".version" ${{ inputs.file }})
+            version=$( jq -r ".version" ${{ inputs.file }} )
             ;;
           "csharp")
-            version=$( grep -o "<Version>.*</Version>" ${{ inputs.file }} | grep -Eo "[0-9]{4}\.[0-9]{2}\.[0-9]+")
+            version=$( grep -o "<Version>.*</Version>" ${{ inputs.file }} | grep -Eo "[0-9]{4}\.[0-9]{2}\.[0-9]+" )
             ;;
         esac
-        echo "::set-output name=new-version::$version"
+        echo "::set-output name=version::$version"
 
 
     - name: Get current released version
+      shell: bash
       id: current-version
       run: |
-        if [ "${{ inputs.override-version }}" != "" ]; then
+        if [ "${{ inputs.override-version }}" == "" ]; then
           # Pull the latest 
           case "${{ inputs.monorepo }}" in
             "true")
@@ -99,11 +112,31 @@ runs:
 
 
     - name: Check versions
+      id: check
+      shell: bash
       run: |
         new_version=${{ steps.new-version.outputs.version }}
         current_version=${{ steps.current-version.outputs.version }}
         if [ "$new_version" == "$current_version" ] && \
         [ "${{ inputs.release-type }}" == "Initial Release" ]; then
           echo "[!] Already released $new_version. Please bump version to continue"
-          exit 1
+          echo "::set-output name=step-failed::true"
+        fi
+
+    - name: Set status
+      id: status
+      shell: bash
+      run: |
+        failed_statuses=(\
+        '${{ steps.validation.outputs.step-failed }}' \
+          '${{ steps.check.outputs.step-failed }}' \
+        )
+
+        echo $failed_statuses
+
+        if [[ "${failed_statuses[@]}" =~ "true" ]]; then
+          echo "::set-output name=status::fail"
+          #exit 1
+        else
+          echo "::set-output name=status::success"
         fi
