Disable `enforce-version-label`

diff --git a/.github/workflows/_enforce-labels.yml b/.github/workflows/_enforce-labels.yml
--- a/.github/workflows/_enforce-labels.yml
+++ b/.github/workflows/_enforce-labels.yml
@@ -16,14 +16,14 @@ jobs:
           echo "### :x: PRs with the hold or needs-qa labels cannot be merged" >> $GITHUB_STEP_SUMMARY
           exit 1
 
-  enforce-version-label:
-    if: ${{ contains(github.event.*.labels.*.name, 'version') }}
-    name: Enforce version label
-    runs-on: ubuntu-22.04
+  # enforce-version-label:
+  #   if: ${{ !contains(github.event.*.labels.*.name, 'version') }}
+  #   name: Enforce version label
+  #   runs-on: ubuntu-22.04
 
-    steps:
-      - name: Check for label
-        run: |
-          echo "PR without the version label cannot be merged."
-          echo "### :x: PR without the version label cannot be merged" >> $GITHUB_STEP_SUMMARY
-          exit 1
+  #   steps:
+  #     - name: Check for label
+  #       run: |
+  #         echo "PR without the version label cannot be merged."
+  #         echo "### :x: PR without the version label cannot be merged" >> $GITHUB_STEP_SUMMARY
+  #         exit 1
