[BRE-1150] Updating test for version check action

diff --git a/.github/workflows/test-version-check.yml b/.github/workflows/test-version-check.yml
--- a/.github/workflows/test-version-check.yml
+++ b/.github/workflows/test-version-check.yml
@@ -51,10 +51,10 @@ jobs:
           version: ${{ matrix.version }}
           validation_type: ${{ matrix.type }}
 
-      # - name: Verify expected failures
-      #   if: ${{ matrix.should-fail == true }}
-      #   run: |
-      #     if [ ${{ steps.run-version-check-action.outcome }} != "failure" ]; then
-      #       echo "Action was expected to fail but did not."
-      #       exit 1
-      #     fi
+      - name: Verify expected failures
+        if: ${{ matrix.should-fail == true }}
+        run: |
+          if [ ${{ steps.run-version-check-action.outcome }} != "failure" ]; then
+            echo "Action was expected to fail but did not."
+            exit 1
+          fi
