add linter for action version pin

diff --git a/.github/workflows/workflow-linter.yml b/.github/workflows/workflow-linter.yml
--- a/.github/workflows/workflow-linter.yml
+++ b/.github/workflows/workflow-linter.yml
@@ -28,7 +28,7 @@ jobs:
                   MODIFIED_EXISTING_WORKFLOWS+=" ${workflow}"
               fi
           done
-          echo "::set-output name=modified-workflows::$MODIFIED_EXISTING_WORKFLOWS"
+          echo "modified-workflows=$MODIFIED_EXISTING_WORKFLOWS" >> $GITHUB_OUTPUT
 
       - name: Workflow Lint
         env:
@@ -36,3 +36,25 @@ jobs:
         uses: bitwarden/gh-actions/lint-workflow@e9dbc0b5edc4f5724124d18b65d8b3fcde767dd9
         with:
           workflows: ${{ steps.changed-workflows.outputs.modified-workflows }}
+
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@b109d83a62e94cf7c522bf6c15cb25c175850b16 # v35.7.12
+        with:
+          files: |
+            .github/workflows/**
+      - name: Check for pinned versions
+        if: steps.changed-files.outputs.any_changed == 'true'
+        run: |
+          MISSING_VERSION_FILES="";
+          IFS=' ' read -ra lines <<< "${{ steps.changed-files.outputs.all_changed_files }}"
+          for line in "${lines[@]}"; do
+            VERSION_PATTERN=cat "${line}" | grep 'uses: ' | awk -F "@" '{print $2}' | awk -F "#" '{print $2}'
+            # v starts a release tag, n is for our actions that have "no release tag" comment
+            if ! echo $VERSION_PATTERN | grep -qE ' v'; then
+              echo "Workflow file ${line} is missing a version tag"
+              MISSING_VERSION_FILES+=" ${line} "
+            fi
+          done
+          echo "### :mega: Workflow files ${MISSING_VERSION_FILES} is missing actions version tag" >> $GITHUB_STEP_SUMMARY
+          exit 1
